version: '3.3'
services:
  db:
    image: 'mysql:8'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp4
    volumes:
      - './start.sh:/docker-entrypoint-initdb.d/start.sh'
      - './database.sql.gz:/database.sql.gz'
    ports:
      - '127.0.0.1:3306:3306'